### ISSUE TITLE
On selecting the mission as a milestone, the proceed button only gets enabled if all mandatory fields are filled not before that. The check is not working properly . replicate this by skipping the image field.

### ISSUE THREAD

**Issue by QAWC2023-GameConquerors** [Fan-Engagement/laurat_admin#18]
On selecting the mission as a milestone, the proceed button only gets enabled if all mandatory fields are filled not before that. The check is not working properly . replicate this by skipping the image field.

**Comment by tushar-gupta01** [comment]
Raised a duplicate issue. hence closing
